"""
Threads Downloader (Playwright-based, concurrency-managed)

Confirmed via live network capture that Threads' post media is not served
through any stable, unauthenticated API - the request that returns real
post data goes through Meta's internal Comet route loader (`/ajax/bz`,
route `comet.threads.BarcelonaPostMediaRoute`), which requires live
session cookies and short-lived tokens generated by the page's own
JavaScript. There's no way to replicate that reliably with a plain HTTP
client, so this drives a real headless Chromium browser instead and
listens for the actual video/image files it downloads while rendering
the post - the browser handles all the cookie/token machinery itself,
same as a real visitor's browser would.

Requirements (see Dockerfile/requirements.txt changes):
    pip install playwright
    playwright install --with-deps chromium

SCALE NOTES - what this is and isn't built for:
No amount of tuning makes a single pod run hundreds of simultaneous
Chromium renders; each one needs real CPU + ~150-300MB RAM. What this
module actually does under heavy load is keep the bot stable rather than
falling over: THREADS_MAX_CONCURRENT_BROWSERS caps how many renders run
in parallel (default 3) and anything beyond that queues and waits its
turn, rather than piling on and exhausting the pod's memory. That's a
meaningfully different guarantee than "instant service for everyone at
once" - worth keeping in mind when reasoning about capacity.

Three concrete things are done here to keep resource usage down:
  1. Concurrency cap (asyncio.Semaphore) - bounds simultaneous renders;
     excess requests queue instead of piling on.
  2. Resource blocking - font loads and known tracker/analytics domains
     are aborted before they download, since they're not needed to
     trigger media loading and were a meaningful chunk of the ~2-4MB per
     page load seen in testing.
  3. One shared Chromium process - launched once (lazily, on first use)
     and reused for every request via isolated browser *contexts*,
     instead of launching+closing a fresh browser per download.

Strategy (in order, each one only runs if the previous one fails):
  1. Headless Chromium capture via the shared browser manager below.
  2. yt-dlp Python API, anonymous - cheap safety net.
  3. yt-dlp CLI with --impersonate chrome, anonymous - final fallback.
"""

from typing import Optional, Union, Dict, List
from urllib.parse import urlparse, urlunparse
import os
import asyncio
import threading
import subprocess
import yt_dlp

from Logic.utils.path import generate_target_dir

THREADS_COOKIES: Optional[str] = os.getenv("Threads_cookies")

USER_AGENT = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36"

VALID_VIDEO_EXTENSIONS = (".mp4", ".mov", ".webm", ".avi")
VALID_IMAGE_EXTENSIONS = (".jpg", ".jpeg", ".png", ".webp", ".heic")
VALID_MEDIA_EXTENSIONS = VALID_VIDEO_EXTENSIONS + VALID_IMAGE_EXTENSIONS

# Real post photos/videos are comfortably larger than this. Avatars, UI
# icons, and sprite images generally aren't. Tune up if avatar/icon images
# are slipping through in testing, or down if a legitimate small image is
# getting filtered out.
MIN_MEDIA_BYTES = 10 * 1024

BROWSER_NAV_TIMEOUT_MS = 30_000
POST_LOAD_SETTLE_MS = 2_000

# How many Threads renders can run at once, process-wide. Excess requests
# queue behind this rather than spawning more concurrent browser load.
# Override via env var without a code change if you need to tune it.
MAX_CONCURRENT_BROWSERS = int(os.getenv("THREADS_MAX_CONCURRENT_BROWSERS", "3"))

# How long a single capture call will wait for its turn + actual render
# time before giving up. Needs to be generous enough to cover real queueing
# under load, not just the render itself.
CAPTURE_RESULT_TIMEOUT_S = 90

# Resource types that are never needed to trigger media loading.
# Deliberately NOT blocking stylesheets - some lazy-load logic can depend
# on layout/visibility (IntersectionObserver etc.), and this hasn't been
# verified safe to block without live testing.
BLOCKED_RESOURCE_TYPES = {"font", "manifest", "websocket", "eventsource", "other"}

# Known third-party tracker/analytics domains - safe to drop entirely,
# never involved in serving the actual post media.
BLOCKED_DOMAINS = (
    "google-analytics.com",
    "googletagmanager.com",
    "doubleclick.net",
    "connect.facebook.net",
    "an.facebook.com",
    "pixel.facebook.com",
    "sentry.io",
    "bugsnag.com",
    "fullstory.com",
    "hotjar.com",
)

# Meta serves UI icons/sprites (not post content) from this static asset
# host - but ALSO serves JS/CSS bundles from the same host, so this only
# blocks *image*-type requests to it, never scripts/stylesheets.
STATIC_ASSET_HOST = "static.cdninstagram.com"

# Meta's CDN encodes a size in the URL query string for resized image
# variants (e.g. "...s150x150..."). Small variants are near-certainly
# thumbnails/avatars for other UI elements, not the post's own full-size
# media - real post images are requested at a much larger size. This one
# is a documented Instagram/Facebook CDN convention that's ASSUMED (not
# yet confirmed live) to carry over to Threads' URLs - worth checking the
# Network tab's total transferred size before/after to confirm it's
# actually having an effect and not silently matching nothing.
import re
_SMALL_SIZE_PATTERN = re.compile(r"[sp](\d+)x(\d+)")
SMALL_IMAGE_DIMENSION_THRESHOLD = 200


def _has_cookies() -> bool:
    return bool(THREADS_COOKIES) and os.path.isfile(THREADS_COOKIES)


def _log(message: str, verbose: bool = False) -> None:
    if verbose:
        print(message)


def _clean_url(url: str) -> str:
    parsed = urlparse(url)
    return urlunparse((parsed.scheme, parsed.netloc, parsed.path, "", "", ""))


def _collect_media_files(target_dir: str) -> List[str]:
    return [f for f in os.listdir(target_dir) if f.lower().endswith(VALID_MEDIA_EXTENSIONS)]


class _ThreadsBrowserManager:
    """
    Owns exactly one headless Chromium instance for the whole process,
    running inside its own dedicated background thread + event loop so it
    can be safely reused across concurrent calls to download_threads()
    (which arrive synchronously, via asyncio.to_thread() elsewhere in the
    bot - Playwright's browser objects aren't safe to share directly
    across arbitrary OS threads, so everything routes through this one
    owning loop instead).

    Public surface is a single synchronous method, capture(), so nothing
    calling into this module needs to know or care that a persistent
    browser + event loop exist behind it.
    """

    def __init__(self) -> None:
        self._loop: Optional[asyncio.AbstractEventLoop] = None
        self._thread: Optional[threading.Thread] = None
        self._playwright = None
        self._browser = None
        self._semaphore: Optional[asyncio.Semaphore] = None
        self._start_lock = threading.Lock()
        self._ready = threading.Event()

    def _ensure_loop_started(self) -> None:
        if self._thread is None:
            with self._start_lock:
                if self._thread is None:
                    def runner() -> None:
                        loop = asyncio.new_event_loop()
                        asyncio.set_event_loop(loop)
                        self._loop = loop
                        self._semaphore = asyncio.Semaphore(MAX_CONCURRENT_BROWSERS)
                        self._ready.set()
                        loop.run_forever()

                    self._thread = threading.Thread(target=runner, daemon=True, name="threads-browser-loop")
                    self._thread.start()

        # Every caller waits here, not just the one that created the
        # thread - otherwise a second thread can see self._thread already
        # set and race ahead to use self._loop before it's actually
        # assigned (this was caught by a concurrency test before shipping).
        self._ready.wait(timeout=10)

    async def _ensure_browser(self, verbose: bool) -> None:
        if self._browser is not None:
            return
        from playwright.async_api import async_playwright

        _log("[Threads] Launching shared Chromium instance (first use this process)...", verbose)
        self._playwright = await async_playwright().start()
        self._browser = await self._playwright.chromium.launch(headless=True)

    @staticmethod
    async def _route_handler(route) -> None:
        request = route.request
        if request.resource_type in BLOCKED_RESOURCE_TYPES:
            await route.abort()
            return
        if any(domain in request.url for domain in BLOCKED_DOMAINS):
            await route.abort()
            return
        await route.continue_()

    async def _async_capture(self, url: str, target_dir: str, verbose: bool) -> List[str]:
        from playwright.async_api import TimeoutError as PlaywrightTimeoutError

        async with self._semaphore:
            await self._ensure_browser(verbose)

            captured: List[Dict] = []
            seen_urls = set()

            async def handle_response(response) -> None:
                try:
                    content_type = response.headers.get("content-type", "")
                except Exception:
                    return

                is_video = content_type.startswith("video/")
                is_image = content_type in ("image/jpeg", "image/png", "image/webp")
                if not (is_video or is_image):
                    return
                if response.url in seen_urls:
                    return

                try:
                    body = await response.body()
                except Exception:
                    return

                if len(body) < MIN_MEDIA_BYTES:
                    return

                seen_urls.add(response.url)
                captured.append({
                    "type": "video" if is_video else "image",
                    "content_type": content_type,
                    "body": body,
                })
                _log(f"[Threads] Captured {content_type} ({len(body)} bytes)", verbose)

            context = await self._browser.new_context(
                user_agent=USER_AGENT,
                viewport={"width": 1280, "height": 1600},
            )
            try:
                await context.route("**/*", self._route_handler)

                page = await context.new_page()
                page.on("response", lambda r: asyncio.ensure_future(handle_response(r)))

                try:
                    await page.goto(url, wait_until="networkidle", timeout=BROWSER_NAV_TIMEOUT_MS)
                except PlaywrightTimeoutError:
                    _log("[Threads] Page load timed out waiting for network idle - continuing with whatever was captured", verbose)
                except Exception as exc:
                    _log(f"[Threads] Page navigation error: {exc}", verbose)

                # Video especially can keep loading segments briefly after
                # networkidle fires - give it a moment.
                await page.wait_for_timeout(POST_LOAD_SETTLE_MS)
            finally:
                await context.close()

        if not captured:
            return []

        has_video = any(item["type"] == "video" for item in captured)
        if has_video:
            captured = [item for item in captured if item["type"] == "video"]

        written: List[str] = []
        for idx, item in enumerate(captured, 1):
            ext = ".mp4" if item["type"] == "video" else "." + item["content_type"].split("/")[1]
            filepath = os.path.join(target_dir, f"media_{idx:03d}{ext}")
            try:
                with open(filepath, "wb") as fh:
                    fh.write(item["body"])
                written.append(filepath)
            except Exception as exc:
                _log(f"[Threads] Failed to write captured media to {filepath}: {exc}", verbose)

        return written

    def capture(self, url: str, target_dir: str, verbose: bool = False) -> List[str]:
        """Synchronous entry point - safe to call from any thread."""
        self._ensure_loop_started()
        future = asyncio.run_coroutine_threadsafe(
            self._async_capture(url, target_dir, verbose), self._loop
        )
        try:
            return future.result(timeout=CAPTURE_RESULT_TIMEOUT_S)
        except Exception as exc:
            _log(f"[Threads] Browser capture failed or timed out: {exc}", verbose)
            return []

    def shutdown(self) -> None:
        """
        Optional - call from the bot's shutdown handler (e.g. on_shutdown
        in index.py) to close the shared browser cleanly instead of
        leaving a Chromium process orphaned when the bot exits. Not
        calling this isn't harmful during normal operation; it just means
        a slightly less tidy shutdown.
        """
        if self._loop is None:
            return

        async def _close():
            if self._browser is not None:
                await self._browser.close()
            if self._playwright is not None:
                await self._playwright.stop()

        try:
            future = asyncio.run_coroutine_threadsafe(_close(), self._loop)
            future.result(timeout=10)
        except Exception:
            pass
        self._loop.call_soon_threadsafe(self._loop.stop)


# One shared manager for the whole process - this is what makes browser
# reuse across concurrent/successive calls actually work.
_browser_manager = _ThreadsBrowserManager()


def shutdown_threads_browser() -> None:
    """Call this from the bot's shutdown handler for a clean exit. See
    _ThreadsBrowserManager.shutdown() docstring for details."""
    _browser_manager.shutdown()


def _build_ydl_opts(target_dir: str, verbose: bool) -> Dict:
    return {
        "outtmpl": os.path.join(target_dir, "media_%(autonumber)03d.%(ext)s"),
        "quiet": not verbose,
        "no_warnings": not verbose,
        "format": "bestvideo*+bestaudio/best",
        "format_sort": ["res", "fps", "tbr", "vcodec:h264"],
        "merge_output_format": "mp4",
        "noplaylist": False,
        "force_ipv4": True,
        "socket_timeout": 15,
    }


def _download_video_cli(url: str, target_dir: str, verbose: bool = False) -> Optional[str]:
    outtmpl = os.path.join(target_dir, "media_%(autonumber)03d.%(ext)s")

    cmd = [
        "yt-dlp",
        "--impersonate", "chrome",
        "--format", "bestvideo*+bestaudio/best",
        "--format-sort", "res,fps,tbr",
        "--merge-output-format", "mp4",
        "--output", outtmpl,
        "--no-playlist",
        url,
    ]

    _log(f"[Threads] Running CLI (anonymous): {' '.join(cmd)}", verbose)

    try:
        subprocess.run(cmd, capture_output=not verbose, text=True, timeout=120)
    except subprocess.TimeoutExpired:
        _log("[Threads] yt-dlp CLI timed out after 120s", verbose)
    except FileNotFoundError:
        _log("[Threads] yt-dlp CLI not found — is it installed?", verbose)
        return None
    except Exception as exc:
        _log(f"[Threads] yt-dlp CLI error: {exc}", verbose)

    files = _collect_media_files(target_dir)
    if not files:
        return None
    if len(files) > 1:
        _log(f"[Threads] ✅ CLI downloaded {len(files)} files → {target_dir}", verbose)
        return target_dir

    file_path = os.path.join(target_dir, files[0])
    _log(f"[Threads] ✅ CLI downloaded: {file_path}", verbose)
    return file_path


def _finalize(target_dir: str, verbose: bool) -> Optional[Union[str, Dict]]:
    files = _collect_media_files(target_dir)
    if not files:
        return None

    if len(files) > 1:
        _log(f"[Threads] ✅ Downloaded {len(files)} files → {target_dir}", verbose)
        return {
            "type": "carousel",
            "file_count": len(files),
            "files": [os.path.join(target_dir, f) for f in files],
            "path": target_dir,
        }

    file_path = os.path.join(target_dir, files[0])
    _log(f"[Threads] ✅ Downloaded: {file_path}", verbose)
    return file_path


def download_threads(url: str, verbose: bool = False) -> Optional[Union[str, Dict]]:
    """
    Download a Threads video or photo post at the highest available quality.

    Returns:
        str  — path to the video file (or directory, for multi-file output)
        dict — carousel metadata (files, path, etc.)
        None — every download strategy failed
    """
    _log(f"[Threads] Processing URL: {url}", verbose)

    url = _clean_url(url)

    target_dir = generate_target_dir("threads")
    os.makedirs(target_dir, exist_ok=True)
    _log(f"[Threads] Target directory: {target_dir}", verbose)

    # Tier 1: shared headless browser capture - the real primary path
    try:
        _log("[Threads] Loading post in headless browser...", verbose)
        _browser_manager.capture(url, target_dir, verbose)
        result = _finalize(target_dir, verbose)
        if result:
            return result
    except ImportError:
        _log("[Threads] playwright not installed — skipping browser capture. "
             "Run: pip install playwright && playwright install --with-deps chromium", verbose)
    except Exception as exc:
        _log(f"[Threads] Browser capture failed: {exc}", verbose)

    # Tier 2: yt-dlp Python API, anonymous - cheap safety net
    _log("[Threads] Trying yt-dlp (Python API, anonymous)...", verbose)
    try:
        with yt_dlp.YoutubeDL(_build_ydl_opts(target_dir, verbose)) as ydl:
            ydl.download([url])
    except Exception as exc:
        _log(f"[Threads] yt-dlp Python API error: {exc}", verbose)

    result = _finalize(target_dir, verbose)
    if result:
        return result

    # Tier 3: CLI with impersonation, anonymous - last resort
    _log("[Threads] Trying yt-dlp CLI with impersonation (anonymous)...", verbose)
    result = _download_video_cli(url, target_dir, verbose)
    if result:
        return result

    _log("[Threads] ❌ All download strategies failed.", verbose)
    return None